variable "ami" {}
variable "instance-type" {}
variable "ansible-SG" {}
variable "subnet-id" {}
variable "keypair" {}
variable "prod-bashscript" {}
variable "prod-playbook" {}
variable "stage-bashscript" {}
variable "stage-playbook" {}
variable "pri-keypair" {}
variable "nexus-ip" {}
variable "newrelic-acct-id" {}
variable "newrelic-user-licence" {}