variable "profile" {}
variable "region" {}
variable "keypath" {}
variable "ami" {}
variable "instance_type" {}
variable "domain-name" {}
variable "email" {}
variable "newrelic-id" {}
variable "newrelic-license-key" {}